esphome:
  name: "test-fan"
  friendly_name: Test Fan
  min_version: 2024.11.0
  name_add_mac_suffix: false

external_components:
  - source: components

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}

fan:
  - platform: ba8206
    id: my_fan
    name: "Fan Controller"
    address: 0x20
    i2c_id: bus_a
    independent_onoff: true

i2c:
  sda: GPIO04
  scl: GPIO05
  scan: true
  id: bus_a
  frequency: 800kHz
  